# .streamlit/config.toml

[theme]
base = "dark"
primaryColor = "#666666"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#2d2d2d"
textColor = "#ffffff"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
headless = true
port = 8501
enableWebsocketCompression = true

[client]
caching = true
showErrorDetails = true

[browser]
gatherUsageStats = false

[global]
suppressDeprecationWarnings = true
dataFrameSerialization = "legacy"
