# Streamlit Configuration for ML Phishing Detector
# MSc Project 2025 - Threat Detection & Resilience Framework
# Author: Towsif Ahmed

[theme]
base = "dark"
primaryColor = "7F00FF"                
backgroundColor = "#1a1a1a"             # Main dark background
secondaryBackgroundColor = "#2d2d2d"    # Sidebar and widget containers
textColor = "#ffffff"                   # White text for readability
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true
headless = true
port = 8501

[client]
caching = true
showErrorDetails = true

[browser]
gatherUsageStats = false

[global]
suppressDeprecationWarnings = true
dataFrameSerialization = "legacy"
