# Streamlit Configuration for ML Phishing Detector
# MSc Project 2025 - Threat Detection & Resilience Framework
# Author: Towsif Ahmed

[theme]
base = "dark"
primaryColor = "#9D4EDD"                # Bright purple for accents (progress bar, buttons)
backgroundColor = "#1a1a1a"             # Dark main background
secondaryBackgroundColor = "#2d2d2d"    # Sidebar and widget background
textColor = "#ffffff"                   # White text
font = "sans serif"                     # Clean, modern font

[server]
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true
headless = true
port = 8501

[client]
caching = true
showErrorDetails = true

[browser]
gatherUsageStats = false

[global]
suppressDeprecationWarnings = true
dataFrameSerialization = "legacy"
